### ISSUE TITLE
Support on Windows?

### ISSUE THREAD

**Issue by trungnt2910** [TheDoctor0/zip-release#12]
Build on Windows gives me this error:

`Error: Container action is only supported on Linux`

Any intention to support Windows? I cannot use ubuntu as my repo contains projects that must be built using UWP.

**Comment by TheDoctor0** [comment]
As stated in README, because of [GitHub Actions limitations](https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions) Docker-based containers only support Linux.
