### ISSUE TITLE
After v0.5 is not working anymore

### ISSUE THREAD

**Issue by sheosi** [TheDoctor0/zip-release#18]
Hi, I'm using the master version of tis action and three days ago now it stoped working. 
What I get is:

```
Run thedoctor0/zip-release@master
sh: /home/runner/work/_actions/thedoctor0/zip-release/master/entrypoint.sh: No such file or directory
```

It really looks like is due to the new version.

**Comment by TheDoctor0** [comment]
I just tested it in my private repository and seems to be working fine.

> sh: /home/runner/work/_actions/thedoctor0/zip-release/master/entrypoint.sh: No such file or directory

This error seems rather disturbing. It may be related to https://github.com/actions/runner/issues/716.

**Comment by TheDoctor0** [comment]
I [changed a path](https://github.com/TheDoctor0/zip-release/commit/13dc28a498568125196e78c8a6acb235615c9c6e) in the run command. You can try if it works for you now.

**Comment by sheosi** [comment]
Sure, the case aligns with that report (I'm using a docker instance). 
BTW, I've tried it and it works now.

**Comment by TheDoctor0** [comment]
Great, I'll tag a release with a fix.
