### ISSUE TITLE
Exclusion format

### ISSUE THREAD

**Issue by anshulahuja98** [TheDoctor0/zip-release#2]
What exactly is the exclusion format for files and folders?

I want to exclude
.git/
.github/
.gitignore

How should I add them to the exclusion list?

**Comment by TheDoctor0** [comment]
Hello.
It's actually quite simple, you can use regex like this:
```exclusions: '*.git*;```

**Comment by anshulahuja98** [comment]
It didn't work properly for multiple paths as I described
Can you perhaps show an example for the files I mentioned above?

`'*.git*  .gitignore'`

I used this but it didn't work on gitignore

**Comment by TheDoctor0** [comment]
If you want to just exclude those two directories and .gitignore you can list them one by one:
```'*.git* *.github* .gitignore'```
It is actually part of definition for one of my private projects and works fine.

You can test this exclusions using from terminal after installing zip package like so:
```zip -r . -x '*.git* *.github* .gitignore'```

**Comment by anshulahuja98** [comment]
Thank you for your support

**Comment by TheDoctor0** [comment]
Glad to help 👍
