### ISSUE TITLE
fully recursive exclusions?

### ISSUE THREAD

**Issue by m4ttheweric** [TheDoctor0/zip-release#24]
Hi, am I struggling figuring out the syntax that will allow me to exclude all files of a given type recursively.

For example, let's say I want to exclude all files ending with `.txt`

`exclusions: *.txt` <- only excludes files at the root dir
`exclusions: */*.txt` <- only excludes files at the 2nd level 

I have tried some other combos, but I think the actual thing here is to pass the `r` modifier to the exclusion flag in 7zip.

Glancing at your source code, it looks like you pass ` -x!`

According to the 7zip docs it looks like if that was changed to ` -xr!` it would allow for recursive searching.

**Comment by TheDoctor0** [comment]
Hello @m4ttheweric!
I have to say that the flag was removed in the latest merged [PR](https://github.com/TheDoctor0/zip-release/pull/22) because it can result in some unexpected issues.
That said I think that I can add a way to force using it, for example by creating a `recursive_exclusions` option.

I will try to get back to it today but if you want you can also fork the repository, make changes and open a pull request - I will be happy to accept and merge it!

**Comment by m4ttheweric** [comment]
thank you so much for doing this so quickly!

I was resorting to writing a batch file to delete files from the workflow run before zipping, but I was running into permissions issues, so this makes it easier.

**Comment by m4ttheweric** [comment]
So, in my initial testing, none of the recursive exclusions are working. The relevant bits of my workflow are below (note I am using multi-line YAML which has not been an issue so far):

```yaml
         - name: Zip MBMD.UI Artifacts
           uses: thedoctor0/zip-release@master
           with:
              filename: ui.zip
              directory: 'MBMD.UI/'
              exclusions: |
                 YuiCompressorMsBuild
                 packages
                 *.csproj
                 *.sln
                 mbmd.png
              recursive_exlusions: |
                 *.config
                 *.as*x.cs
                 *.designer.cs
                 *.Master.cs
```

Do I need to do something different here? The exclusions are all working, but the recursive_exlusions are not working across the board.
