### ISSUE TITLE
Spaces in path or filename does not work

### ISSUE THREAD

**Issue by jwomack** [TheDoctor0/zip-release#25]
Spaces in $INPUT_FILENAME or $INPUT_PATH does not work.
The fix would be to double quote the variable occurrences, or at least on the lines with zip.

**Comment by Luke18033** [comment]
It's still broken, seems like that commit isn't actually on any branch or something? It works if I tell it to use that exact commit, but not on latest main.

**Comment by TheDoctor0** [comment]
@Luke18033 good catch. I think that the commit may have been lost by force-push at some point. I'll just re-apply the changes and make a quick release in a second.
