### ISSUE TITLE
latest release broke zipping assets in our pipeline

### ISSUE THREAD

**Issue by lstebner** [TheDoctor0/zip-release#26]
hello, I'm not exactly sure why, but the latest release broke zipping of our assets. the error was simply that there is "nothing to do", so I'm guessing it's related to the way we're specifying what to zip using asterisk notation, but I'm not entirely sure. happy to provide more info to help debug if you can point me to what would help. hopefully this was unintentional. one thing that might be useful to know is that we are using lerna to manage this repository. 

here's a screenshot of the failing pipeline:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/628757/168686921-992fbb46-cf74-4f39-bf60-adceeed4195f.png">

we fixed it by specifying `thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657` instead of `@master`

**Comment by TheDoctor0** [comment]
HI @lstebner, I assume that quoting parameters broke build in your case.
I will quickly revert it because it probably affected other people.
If you can provide a dummy directory structure to replicate this issue, it would be great!

**Comment by lstebner** [comment]
thanks for the quick revert! I haven't had a chance to put together something for you yet, but I will try to get to it over the weekend though I'm a little bit unsure how well I'll be able to do it. managing workflows isn't my expertise, I just ended up being the person debugging the day it happened. I suspect the quoting made the `*` get interpreted literally though, but maybe there is some other sort of syntax that should be used there? or maybe quoting is the responsibility of the person using this tool instead of the tool itself?

**Comment by etiennenoel** [comment]
Hi, I am now getting the following error:

`Error: Unable to resolve action `TheDoctor0/zip-release@master`, unable to find version `master``

**Comment by lstebner** [comment]
@etiennenoel that's actually related to #27 which looks like it ended up affecting some other people too. switching to `main` will fix (if you're able to do that), but you might want to jump over to that issue instead of this one
