### ISSUE TITLE
please update `master` to `main`

### ISSUE THREAD

**Issue by lstebner** [TheDoctor0/zip-release#27]
please update the name of the main branch to match the latest community standards as it written about here https://github.com/github/renaming

**Comment by TheDoctor0** [comment]
Done :smile:

**Comment by pedrogomesesfera** [comment]
Greetings, I understand that this improvement was done to match the community standards, but this have affected my company workflows directly. We have dozens of repositories which point to your master branch, and this update will break our git workflows in all of them, so I would like to know if it would be possible to create the master branch again to maintain compatibility

**Comment by lstebner** [comment]
@TheDoctor0 sorry I didn't think about this breaking things for people, you might want to dup `main` as `master` so that people can switch over, but I would still leave `main` as the primary branch for future improvements. maybe a note in the README about the change too

**Comment by TheDoctor0** [comment]
@pedrogomesesfera, the `master` branch has been created to maintain backward compatibility.
