### ISSUE TITLE
Using path as base directory for files inside the zip file

### ISSUE THREAD

**Issue by bierdosenhalter** [TheDoctor0/zip-release#29]
When using 
```     - name: Zip package Linux-x64
        uses: thedoctor0/zip-release@main
        with:
          type: 'tar'
          path: 'publish/linux64/'
          exclusions: '*.pdb'
          filename: 'linux-x64.tar.gz'
```
i get a tar file with my files in the folders 
**linux-x64.tar.gz\publish\linux64\\**

 but it would be way nicer if they would be in the root of the zip file 
**linux-x64.tar.gz\\**

**Comment by TheDoctor0** [comment]
Hello @bierdosenhalter!
You can use the existing `directory` parameter to achieve that.

### `directory`
Default: `.`

The working directory where the zip or tar actually runs.

### `path`
Default: `.`

The path to the files or directory that should be archived, relative to `directory`.
