### ISSUE TITLE
Upload Release fails

### ISSUE THREAD

**Issue by atanasantonov** [TheDoctor0/zip-release#32]
Hello,

Thank you for the great action. It was working great but now there is an error with the Upload Release step.

Run ncipollo/release-action@v1
...
Error: Error 404: Not Found

Best,
Atanas

**Comment by TheDoctor0** [comment]
@atanasantonov the action is still available in the Marketplace: https://github.com/marketplace/actions/create-release.
That said, can you try with `@v1.12.0` instead of `@v1` which should get the currently latest version?
