### ISSUE TITLE
tar only allows for one exclusion

### ISSUE THREAD

**Issue by Athanasius** [TheDoctor0/zip-release#33]
For the zip archive type `entrypoint.sh` iterates over `$INPUT_EXCLUSIONS` to add a `-x!` argument per 'word'.

But for the tar archive type it's just doing:
```bash
tar -zcvf $INPUT_FILENAME --exclude=$INPUT_EXCLUSIONS $INPUT_PATH 
```
which means that every word after the first in INPUT_EXCLUSIONS instead is treated by tar as an input path, the exact opposite of what is wanted.

And if you use this with `directory: '..'` as I'm doing then you get errors like:
```bash
tar: .editorconfig: Cannot stat: No such file or directory
```
because tar can't find the cited filenames/globs in order to use them as input files.

So, the same looping as is done for zip needs to be implemented for tar.  For now I'm just going to use a manual `script: |` for my use case.

**Comment by TheDoctor0** [comment]
Hello @Athanasius.
Thank you for pointing out the issue with handling multiple exclusions for `tar` - [I just implemented it](https://github.com/TheDoctor0/zip-release/releases/tag/0.6.3).
