### ISSUE TITLE
Exclude folder

### ISSUE THREAD

**Issue by seelenverwandter1** [TheDoctor0/zip-release#34]
I'm trying to exclude a folder and already tried
fullpath/exclude/*
/fullpath/exclude/* 
/fullpath/exclude/\*
and much more, but nothing worked.
What is the right Syntax for this?

`name: Create Archive Light
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "1Timo1"
        git config pull.rebase false
        git pull
        rm -f BingoRPGomme.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'BingoRPGommeLight.zip'
        exclusions: '/assets/minecraft/textures/gui/\* *.git* /*node_modules/* .editorconfig *.zip'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force`

**Comment by TheDoctor0** [comment]
Hello @1Timo1!
Are you sure that the `/fullpath/exclude/` is the path from root directory?
You can probably try `*/fullpath/exclude/*` and I assume in your case that would be `*/assets/minecraft/textures/gui/*`.

**Comment by 1Timo1** [comment]
Tried that, but didn't work.
Thats the directory i want to exclude 
https://github.com/1Timo1/BingoRPGomme/tree/main/assets/minecraft/textures/gui
and thats my action yml file 
https://github.com/1Timo1/BingoRPGomme/blob/main/.github/workflows/light.yml

**Comment by TheDoctor0** [comment]
@1Timo1 is result the same with `/*assets/minecraft/textures/gui/container/*`?

**Comment by TheDoctor0** [comment]
I tested it manually and looks like `*assets/minecraft/textures/gui*` works as expected.

**Comment by 1Timo1** [comment]
That's weird. Could something else be wrong in my file?
