### ISSUE TITLE
Symlinking by default would be nice.

### ISSUE THREAD

**Issue by mcourteaux** [TheDoctor0/zip-release#37]
I'd suggest adding a `keep_symlinks` option. The `zip` command needs an additional `--symlinks` to avoid copying the file pointed to, instead of just archiving the symlink.

Tar does this by default.

This behavior makes sense when you are packaging stuff for release (so I'd even consider making this default to True).

**Comment by TheDoctor0** [comment]
Hey @mcourteaux.
I agree that it would make sense to make the behavior consistent, so I'll make that a default for `zip`.

**Comment by mcourteaux** [comment]
Yeah, for me I was packaging a lot of `*.so` files double or tripple (just because of the way the symlinking with the version numbers works). I even tried `--symlinks` in custom, but it didn't work. Perhaps, the docker image has a zip-executable that doesn't have that function?

That's why I switched to `.tar.gz` for the linux release.

**Comment by TheDoctor0** [comment]
@mcourteaux you may try again with the `--symlinks` custom parameter as there was [an issue](https://github.com/TheDoctor0/zip-release/commit/fdf9970c07d0d6f7d2145114ce8b473a3a076c1a) with it for the `zip` command as that was also fixed in the latest release.

**Comment by mcourteaux** [comment]
Aaah that most likely explains the behavior I observed! Good catch! To be honest, I don't have the need to test it again, but the code fix you linked will almost certainly make it work indeed. Thanks for looking into this!
