### ISSUE TITLE
Exclusions not working with specifing a path

### ISSUE THREAD

**Issue by varndellwagglebee** [TheDoctor0/zip-release#41]
I have tried several iterations of exclusions;

*./app
*.app/*
*/app/*
./app
*/app/*

  - name: npm install, build, and test
        working-directory: 'ui/${{env.AZURE_WEBAPP_NAME}}'
        run: |
           npm install
           npm run build --if-present
           #npm run test --if-present
           
      - name: Zip artifacts
        uses: TheDoctor0/zip-release@0.7.1
        with:
         type: 'zip'
         path: ./ui/${{env.AZURE_WEBAPP_NAME}}/*   
         filename: ${{ env.BRANCH_NAME}}.zip               
         exclusions: '*.app *.cert /*node_modules/* *.test'

  env:
    AZURE_WEBAPP_NAME: glypheditor
    AZURE_WEBAPP_PACKAGE_PATH: /ui
    NODE_VERSION: 18.x
    BRANCH_NAME: develop
    BUILD_CONFIGURATION: Debug
    VERSION_SUFFIX: develop
    SLOT: staging
    INPUT_FILENAME: develop.zip
    INPUT_PATH: ./ui/glypheditor/*
    INPUT_DIRECTORY: .
    INPUT_EXCLUSIONS: 
    INPUT_RECURSIVE_EXCLUSIONS: 
    INPUT_CUSTOM: 
    INPUT_TYPE: zip

**Comment by TheDoctor0** [comment]
Hey @varndellwagglebee.
Can you share how your directory structure looks like?

**Comment by varndellwagglebee** [comment]
Thanks for your reply.  I have since restructured my project.  I will reach back if I have further issues.
