### ISSUE TITLE
Space in file name / path / directory fails action

### ISSUE THREAD

**Issue by amamic1803** [TheDoctor0/zip-release#46]
If you put a space in file name, path, or directory, this action fails. This is because when it gets passed to zip command, if there is a space in path/directory/filename, it gets interpreted as more than one argument which leads to failure. If any of these include spaces, they should be put inside double quotes before passing to zip command.
For example:
`path: boards/3D Pinball for Windows - Space Cadet/.`
fails because there are spaces in folder name.

**Comment by DarkLord76865** [comment]
Note that provided example that fails can't be fixed by adding double quotes like this:
`path: "boards/3D Pinball for Windows - Space Cadet/."`
Because actions don't save those quotes so it doesn't really change anything.
