### ISSUE TITLE
entrypoint.sh: 'unexpected operator' from 0.4.0 updates

### ISSUE THREAD

**Issue by agc93** [TheDoctor0/zip-release#5]
After my build updated to 0.4.0 (probably should have pinned the version in hindsight 😄 ), my [existing Action](https://github.com/agc93/beatvortex/blob/master/.github/workflows/build.yml#L52) started failing silently during build.

From what I can tell, this is from the addition of the [`[ "$5" == "zip" ]`](https://github.com/TheDoctor0/zip-release/blob/master/entrypoint.sh#L14) and [`[ "$5" == "tar" ]`](https://github.com/TheDoctor0/zip-release/blob/master/entrypoint.sh#L25) operators, which `sh` doesn't support.

If you want to see an example, [this action](https://github.com/agc93/beatvortex/blob/master/.github/workflows/build.yml#L52) results in [this log](https://github.com/agc93/beatvortex/runs/831505116?check_suite_focus=true) with the following error:

```text
📦 Creating zip archive...


✔ Successfully created zip archive.

/entrypoint.sh: 14: [: zip: unexpected operator
/entrypoint.sh: 25: [: zip: unexpected operator
```

---

If you need any more info, just let me know 👍

**Comment by TheDoctor0** [comment]
Oh, you're right, I totally forgot that it's a POSIX not a Bash script.
I'll fix it as soon as possible.

> probably should have pinned the version in hindsight

Yeah, that's probably a good idea to add a version constraint 😄
