### ISSUE TITLE
Error Name not matched multiple paths with 0.7.5

### ISSUE THREAD

**Issue by hannesroth88** [TheDoctor0/zip-release#50]
suddenly getting the following error although the folders / files exist:
"zip warning: name not matched: dist node_modules package.json"

Using the latest 0.7.5

Here's the workflow:
      - name: Zip the folder
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: '.'
          path: 'dist node_modules package.json'
          
          
After switching to thedoctor0/zip-release@0.7.1 it works again

**Comment by TheDoctor0** [comment]
Hey @hannesroth88.
I guess it's back to the https://github.com/TheDoctor0/zip-release/commit/e1b2518b11867a1ce3334b5b42c781f468981032 as a result of the https://github.com/TheDoctor0/zip-release/pull/47.
I will revert that change once again and suggest a different approach in README for people who have whitespace in filenames / paths.

**Comment by TheDoctor0** [comment]
@hannesroth88 you can use the latest release.
